// <auto-generated />
namespace ValidationWeb.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrgLevelReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrgLevelReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201908261759334_OrgLevelReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
