// <auto-generated />
namespace ValidationWeb.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddProgramAreas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProgramAreas));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271659362_AddProgramAreas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
