// <auto-generated />
namespace ValidationWeb.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SoftDeleteSchoolYears : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SoftDeleteSchoolYears));
        
        string IMigrationMetadata.Id
        {
            get { return "202103221745515_SoftDeleteSchoolYears"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
