IF EXISTS (SELECT * 
		FROM INFORMATION_SCHEMA.ROUTINES
		WHERE ROUTINE_NAME = 'ValidMARSSNumberFormat'
			AND ROUTINE_SCHEMA = 'dbo')
	DROP FUNCTION [dbo].ValidMARSSNumberFormat
GO

CREATE FUNCTION dbo.ValidMARSSNumberFormat (@MARSSNumber VARCHAR(200))

RETURNS BIT 

BEGIN

DECLARE @ValidMARSSNumber AS BIT

SELECT @ValidMARSSNumber = 
	   CASE
		WHEN @MARSSNumber LIKE '%[^0-9]%' THEN 0
		WHEN LEN(LTRIM(RTRIM(@MARSSNumber))) <> 13 THEN 0
		WHEN LEFT(@MARSSNumber,4) IN ('0000','5555') THEN 0
	   ELSE 1
	   END
RETURN @ValidMARSSNumber;

END;